### ISSUE TITLE
WebGis architecture: OpenLayers 3/Leaflet

### ISSUE THREAD

**Issue by lukdal** [scarpazi/oa2#29]
Testing OpenLayers 3 in Google Chrome, with zoom, pan, rotation and reset rotation controls.

![schermata 2014-05-18 alle 14 07 24](https://cloud.githubusercontent.com/assets/6459612/3007456/44a54214-de88-11e3-9155-f93be114032d.png)

**Comment by lukdal** [comment]
First geographic Data Entry/Data Selection prototype. 
WMS base layers on display, set with different opacity levels.

![schermata 2015-02-16 alle 18 34 52](https://cloud.githubusercontent.com/assets/6459612/6216572/c608d716-b60b-11e4-86f9-ba95f82c2a84.png)

**Comment by lukdal** [comment]
Simple and advanced search features added.
Sections re-arranged in container.
![schermata 2015-02-19 alle 16 45 58](https://cloud.githubusercontent.com/assets/6459612/6270023/52dfc184-b857-11e4-8654-894bea7b1321.png)

**Comment by lukdal** [comment]
Vector data (Shapefiles) displayed in Leaflet through WMS request from GeoServer. 
Also considering using GeoJSON format for vector data in Leaflet.
![schermata 2015-02-23 alle 17 20 11](https://cloud.githubusercontent.com/assets/6459612/6331589/5e339caa-bb80-11e4-8ffc-5bdc4cc40054.png)

**Comment by scarpazi** [comment]
Very well!

A few considerations:
* good idea to try GeoJSON to load Geoserver WFS layers, guess it's probably the best way;
* you'll have to find a way to avoid pixelated map edges (tile size?);
* I'm not sure, but if I remember right there should also be a WFS plugin for Leaflet.

To sum it up: we still have time to test some different approaches, let's try them all and see which one is best for us. Always keeping in mind that for an optimal management of vector data we'll have to use OpenLayers (but that will come in a future stage...)

**Comment by lukdal** [comment]
Feature request on GeoJSON vector layers (castles and city boundaries) in Leaflet.
Next step: managing layers dinamically.
![schermata 2015-02-25 alle 11 52 57](https://cloud.githubusercontent.com/assets/6459612/6369342/acc444a8-bce5-11e4-885e-65bf15705bca.png)

**Comment by lukdal** [comment]
Layer Controls (base maps and overlays) added.
![schermata 2015-02-26 alle 12 09 34](https://cloud.githubusercontent.com/assets/6459612/6390883/ab715660-bdb0-11e4-8e97-2697ab62f620.png)

**Comment by lukdal** [comment]
Features are now included in the Wakanda widget.
![schermata 2015-03-01 alle 19 58 30](https://cloud.githubusercontent.com/assets/6459612/6432458/e1420588-c052-11e4-93e4-300a265964ea.png)

**Comment by lukdal** [comment]
Right click-menu added. (Features: show coordinates, center map, zoom in, zoom out)
Next step: working on client/server interactions.
![schermata 2015-03-05 alle 11 10 55](https://cloud.githubusercontent.com/assets/6459612/6502934/6377d140-c328-11e4-94f7-b47e6b5b8115.png)
![schermata 2015-03-05 alle 11 13 39](https://cloud.githubusercontent.com/assets/6459612/6502961/b4354cf2-c328-11e4-948d-6ef975b24c4a.png)

**Comment by lukdal** [comment]
Added support for drawing and editing vectors and markers.
Now we have to find a way to bind them to datasources in Wakanda (like we can do now with points, through Leaflet widget).
![schermata 2015-03-06 alle 14 58 52](https://cloud.githubusercontent.com/assets/6459612/6526365/58ee98f0-c411-11e4-84ea-a8ebbb4bb2ba.png)

**Comment by lukdal** [comment]
Found a way to capture new vector layers created with Leaflet.Draw, convert them to geojson, then stringify them for saving.
Now I have to bind them to Wakanda's datasources.


              // Leaflet.draw controls

          var drawnItems = new L.FeatureGroup();
          this._map.addLayer(drawnItems);
          var drawControl = new L.Control.Draw({
          edit: {
          featureGroup: drawnItems
          }
          });
          this._map.addControl(new L.Control.Draw({
			edit: { featureGroup: drawnItems }
		}));

		this._map.on('draw:created', function (e) {
       var type = e.layerType;
       var layer = e.layer;

       var shape = layer.toGeoJSON();
       var shape_for_db = JSON.stringify(shape);
       drawnItems.addLayer(layer)
      });
